apiVersion: v1
appVersion: v1.77.2
description: Victoria Metrics Alert - executes a list of given MetricsQL expressions
  (rules) and sends alerts to Alert Manager.
name: victoria-metrics-alert
sources:
- https://github.com/VictoriaMetrics/helm-charts
version: 0.4.32
