{
 "title": "Kubernetes Overview",
 "description": "Assorted metrics for an overview of your cluster",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Step", "query": "30s,1m,5m,15m,1h" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Kubernetes Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(kubernetes_build_info{job=\"kubernetes-apiservers\"})",
     "legendFormat": "{{ git_version }}"
    }
   ]
  },
  {
   "title": "Container Runtime Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1, kube_node_info{job=\"kube-state-metrics\"})",
     "legendFormat": "{{ container_runtime_version }}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "ETCD servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(etcd_server_version{job=\"kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Abnormal Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_pod_status_phase{job=\"kube-state-metrics\", phase!~\"Running|Succeeded\"} == 1) OR ON(namespace, pod) (kube_pod_status_ready{job=\"kube-state-metrics\", condition=\"true\"} == 0)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Abnormal Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{job=\"kube-state-metrics\"} != 1) OR vector(0)"
    }
   ]
  },
  {
   "title": "ETCD Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "etcd_server_version", "legendFormat": "{{ server_version }}" }
   ]
  },
  {
   "title": "Platform",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1, kubernetes_build_info{job=~\"kubernetes-apiservers|kubernetes-nodes\"})",
     "legendFormat": "{{ platform }}"
    }
   ]
  },
  {
   "title": "Abnormal Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_node_status_condition{job=\"kube-state-metrics\", condition=\"Ready\", status!=\"true\"} == 1) OR ON(node) (kube_node_status_condition{job=\"kube-state-metrics\", condition!=\"Ready\", status=\"true\"} == 1)) OR vector(0)"
    }
   ]
  },
  {
   "title": "Leaderless ETCD servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(etcd_server_has_leader == 0) OR vector(0)"
    }
   ]
  },
  {
   "title": "APIServer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "APIServer Requests",
     "type": "timeseries",
     "description": "The number of requests handled by kube-apiserver per second, excluding CONNECT, WATCH, and WATCHLIST",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(apiserver_request_total{job=\"kubernetes-apiservers\", resource!=\"\", group!=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\"}[5m])",
       "legendFormat": "{{ verb }} {{ resource }}.{{ group }}"
      },
      {
       "expr": "rate(apiserver_request_total{job=\"kubernetes-apiservers\", resource!=\"\", group=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\"}[5m])",
       "legendFormat": "{{ verb }} {{ resource }}"
      }
     ]
    },
    {
     "title": "Slow APIServer Requests",
     "type": "timeseries",
     "description": "The number of requests per second that have taken kube-apiserver more than 3 seconds to handle, excluding CONNECT, WATCH, and WATCHLIST",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(apiserver_request_duration_seconds_bucket{job=\"kubernetes-apiservers\", resource!=\"\", group!=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\", le=\"+Inf\"}[5m])\n  - IGNORING(le) rate(apiserver_request_duration_seconds_bucket{job=\"kubernetes-apiservers\", le=\"3\"}[5m])",
       "legendFormat": "{{ verb }} {{ resource }}.{{ group }}"
      },
      {
       "expr": "rate(apiserver_request_duration_seconds_bucket{job=\"kubernetes-apiservers\", resource!=\"\", group=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\", le=\"+Inf\"}[5m])\n  - IGNORING(le) rate(apiserver_request_duration_seconds_bucket{job=\"kubernetes-apiservers\", le=\"3\"}[5m])",
       "legendFormat": "{{ verb }} {{ resource }}"
      }
     ]
    },
    {
     "title": "Failed APIServer Requests",
     "type": "timeseries",
     "description": "The number of requests per second that were handled by kube-apiserver and returned 4xx or 5xx, excluding CONNECT, WATCH, and WATCHLIST",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(apiserver_request_total{job=\"kubernetes-apiservers\", resource!=\"\", group!=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\", code=~\"(4|5)\\\\d{2}\"}[5m])",
       "legendFormat": "{{ verb }} {{ resource }}.{{ group }} {{ code }}"
      },
      {
       "expr": "rate(apiserver_request_total{job=\"kubernetes-apiservers\", resource!=\"\", group=\"\", verb!~\"CONNECT|WATCH|WATCHLIST\", code=~\"(4|5)\\\\d{2}\"}[5m])",
       "legendFormat": "{{ verb }} {{ resource }} {{ code }}"
      }
     ]
    },
    {
     "title": "APIServer Response Volume",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(apiserver_response_sizes_sum{job=\"kubernetes-apiservers\"}[5m])) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "APIServer Watch Events Volume",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(apiserver_watch_events_sizes_sum{job=\"kubernetes-apiservers\"}[5m])) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "APIServer Watch Event Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(apiserver_watch_events_total{job=\"kubernetes-apiservers\", group!=\"\"}[5m])) by (group, version, kind)",
       "legendFormat": "{{ group }}/{{ version }}.{{ kind }}"
      },
      {
       "expr": "sum(rate(apiserver_watch_events_total{job=\"kubernetes-apiservers\", group=\"\"}[5m])) by (version, kind)",
       "legendFormat": "{{ version }}.{{ kind }}"
      }
     ]
    }
   ]
  },
  {
   "title": "ETCD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "ETCD Leader Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "label_join(etcd_server_has_leader, \"etcd_key\", \"/\", \"instance\", \"job\")"
      },
      {
       "expr": "label_join(etcd_server_is_leader, \"etcd_key\", \"/\", \"instance\", \"job\")"
      }
     ]
    },
    {
     "title": "ETCD WAL Fsync Latency - P99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(etcd_disk_wal_fsync_duration_seconds_bucket[5m]))",
       "legendFormat": "{{ job }} - {{ instance }}"
      }
     ]
    },
    {
     "title": "ETCD Committed Proposals",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "rate(etcd_server_proposals_committed_total[5m])",
       "legendFormat": "{{ job }} - {{ instance}}"
      }
     ]
    },
    {
     "title": "ETCD Leader Change Observed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "per hour" } },
     "targets": [
      {
       "expr": "increase(etcd_server_leader_changes_seen_total[1h])",
       "legendFormat": "{{ job }} - {{ instance}}"
      }
     ]
    },
    {
     "title": "ETCD Commit to Disk Latency - P99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, rate(etcd_disk_backend_commit_duration_seconds_bucket[5m]))",
       "legendFormat": "{{ job }} - {{ instance }}"
      }
     ]
    },
    {
     "title": "ETCD Failed Proposals",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "rate(etcd_server_proposals_failed_total[5m])",
       "legendFormat": "{{ job }} - {{ instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU Saturation - Top 10",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(10, rate(container_cpu_usage_seconds_total{job=\"kubernetes-nodes-cadvisor\", pod!=\"\", container!=\"\"}[5m]) / ON(namespace, pod, container) GROUP_LEFT max(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\"}) without (node))",
       "legendFormat": "{{ namespace }}/{{ pod }}: {{ container }}"
      }
     ]
    },
    {
     "title": "Container Memory Saturation - Top 10",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(10, container_memory_working_set_bytes{job=\"kubernetes-nodes-cadvisor\", pod!=\"\", container!=\"\"} / ON(namespace, node, pod, container) GROUP_LEFT max(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\"}) without (node))",
       "legendFormat": "{{ namespace }}/{{ pod }}: {{ container }}"
      }
     ]
    },
    {
     "title": "PVC Space Saturation - Top 10",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "topk(10, kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes {job=\"kubernetes-nodes\"})",
       "legendFormat": "{{ namespace }}/{{ persistentvolumeclaim }}"
      }
     ]
    },
    {
     "title": "Node CPU Saturation - Top 10",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node_load5 / count(max(node_cpu_seconds_total{job=\"node-exporter\"}) without (mode)) without (cpu)",
       "legendFormat": "{{ node }}"
      },
      { "expr": "vector(1)", "legendFormat": "reference" }
     ]
    },
    {
     "title": "Node Memory Saturation - Top 10",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(10, 1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes {job=\"node-exporter\"})",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Filesystem Space Saturation - Top 10",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - node_filesystem_avail_bytes{fstype!=\"tmpfs\", job=\"node-exporter\"} / node_filesystem_size_bytes{job=\"node-exporter\"}",
       "legendFormat": "{{ node }}: {{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workqueue Work Duration - P99",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(workqueue_work_duration_seconds_bucket{job=~\"kubernetes-pods|kubernetes-apiservers|kubernetes-nodes\"}[5m])) by (job, name, le))",
       "legendFormat": "{{ job }} - {{ name }}"
      }
     ]
    },
    {
     "title": "Non-empty Workqueues",
     "type": "timeseries",
     "description": "The number of items in a Workqueue that are waiting to be processed. This includes Workqueues from any components.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(workqueue_depth{job=~\"kubernetes-apiservers|kubernetes-pods|kubernetes-nodes\"}) by (job, name)",
       "legendFormat": "{{ job }} - {{ name }}"
      }
     ]
    },
    {
     "title": "Workqueue Retried Items",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(workqueue_retries_total{job=~\"kubernetes-apiservers|kubernetes-pods|kubernetes-nodes\"}[5m])) by (job, name)",
       "legendFormat": "{{ job }} - {{ name }}"
      }
     ]
    },
    {
     "title": "Kubelet Runtime OP Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "cpm" } },
     "targets": [
      {
       "expr": "increase(kubelet_runtime_operations_errors_total{job=\"kubernetes-nodes\"}[1m])",
       "legendFormat": "{{ operation_type }} - {{ instance }}"
      }
     ]
    },
    {
     "title": "Unavailable APIServices",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(max(aggregator_unavailable_apiservice{job=\"kubernetes-apiservers\"}) by (name)) == 1",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Failed Monitoring Targets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "up == 0", "legendFormat": "{{ job }} - {{ instance }}" }
     ]
    }
   ]
  }
 ]
}